### ISSUE TITLE
Help upgrading

### ISSUE THREAD

**Issue by TheCableGuy99** [themoosman/weewx-ambientweatherapi-json#31]
Hi,

I'm running this on an Ubuntu 22.04 VM.

I've tried to upgrade but it's failed and won't start so reverted it to an image backup to get it up and running again.

Please could you confirm the process to upgrade it?

Many thanks.

**Comment by themoosman** [comment]
What version of WeeWX are you running?

**Comment by themoosman** [comment]
On the terminal run `weewxd --version`

**Comment by themoosman** [comment]
Got it.  Let me spin up an environment and test it out.

**Comment by themoosman** [comment]
What was the problem?

**Comment by themoosman** [comment]
It almost seems it may have added duplicate lines to the config.  The section added to the weewx.conf should look similar to:  https://github.com/themoosman/weewx-ambientweatherapi-json/blob/master/weewx.conf

**Comment by jithatsonei** [comment]
also had this issue, the error was:

```
May 08 21:35:53 jellyfin weewxd[30029]: CRITICAL __main__: Caught unrecoverable exception:
May 08 21:35:53 jellyfin weewxd[30029]: CRITICAL __main__:     ****  AmbientWeatherAPI.__init__() takes 1 positional argument but 3 were >
May 08 21:35:53 jellyfin weewxd[30029]: CRITICAL __main__:     ****  Traceback (most recent call last):
May 08 21:35:53 jellyfin weewxd[30029]: CRITICAL __main__:     ****    File "/usr/share/weewx/weewxd.py", line 160, in main
May 08 21:35:53 jellyfin weewxd[30029]: CRITICAL __main__:     ****      engine = weewx.engine.StdEngine(config_dict)
May 08 21:35:53 jellyfin weewxd[30029]: CRITICAL __main__:     ****               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
May 08 21:35:53 jellyfin weewxd[30029]: CRITICAL __main__:     ****    File "/usr/share/weewx/weewx/engine.py", line 89, in __init__
May 08 21:35:53 jellyfin weewxd[30029]: CRITICAL __main__:     ****      self.loadServices(config_dict)
May 08 21:35:53 jellyfin weewxd[30029]: CRITICAL __main__:     ****    File "/usr/share/weewx/weewx/engine.py", line 157, in loadServices
May 08 21:35:53 jellyfin weewxd[30029]: Traceback (most recent call last):
May 08 21:35:53 jellyfin weewxd[30029]:   File "/usr/share/weewx/weewxd.py", line 265, in <module>
May 08 21:35:53 jellyfin weewxd[30029]: CRITICAL __main__:     ****      obj = weeutil.weeutil.get_object(svc)(self, config_dict)
May 08 21:35:53 jellyfin weewxd[30029]:     main()
May 08 21:35:53 jellyfin weewxd[30029]:   File "/usr/share/weewx/weewxd.py", line 160, in main
May 08 21:35:53 jellyfin weewxd[30029]:     engine = weewx.engine.StdEngine(config_dict)
May 08 21:35:53 jellyfin weewxd[30029]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
May 08 21:35:53 jellyfin weewxd[30029]:   File "/usr/share/weewx/weewx/engine.py", line 89, in __init__
May 08 21:35:53 jellyfin weewxd[30029]:     self.loadServices(config_dict)
May 08 21:35:53 jellyfin weewxd[30029]:   File "/usr/share/weewx/weewx/engine.py", line 157, in loadServices
May 08 21:35:53 jellyfin weewxd[30029]:     obj = weeutil.weeutil.get_object(svc)(self, config_dict)
May 08 21:35:53 jellyfin weewxd[30029]:           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
May 08 21:35:53 jellyfin weewxd[30029]: TypeError: AmbientWeatherAPI.__init__() takes 1 positional argument but 3 were given
May 08 21:35:53 jellyfin weewxd[30029]: CRITICAL __main__:     ****            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
May 08 21:35:53 jellyfin systemd[1]: weewx.service: Main process exited, code=exited, status=1/FAILURE
```

but removing the 
It was this stopping it:
user.ambientweatherapi.AmbientWeatherAPI bit `weectl extension install` puts in the config resolved it
